### ISSUE TITLE
Add solution hashes (and solution checker) 

### ISSUE THREAD

**Issue by jxu** [luckytoilet/projecteuler-solutions#6]
So users can check their solutions without spoiling them.

Here is a method to generate hashes. 
First I convert Solutions.md into a machine-readable form (with unix newlines) where line n is just the solution string for problem n. 

    cat Solutions.md | dos2unix | tail -n +6 | head -n -2 | perl -pe 's/^[0-9]+\.//gm' | awk '{$1=$1}1' > solutions.txt

Then create a file with a md5 hash of the solution string if it exists, else a blank line. 

    while read -r line; do if [ -z $line ] ; then echo; else echo -n $line | md5sum | cut -f1 -d ' '; fi; done < solutions.txt > project_euler_md5.txt 

Here is the md5 list https://gist.github.com/jxu/4a36e1752a27fb6506ac0927c09bd5fb 

To check your answer for problem n, you can manually hash your answer and check against the md5 file:

```
$ sed '10q;d' project_euler_md5.txt 
d915b2a9ac8749a6b837404815f1ae25
$ echo -n '1234' | md5sum | cut -f1 -d' '
81dc9bdb52d04dc20036dbd8313ed055
```

If you like the idea of adding this to the repo I can make a quick PR (probably with a python checker script for Windows friends)

**Comment by luckytoilet** [comment]
This repo will only host the solutions. You are welcome to make your own repo if you like, although this project might already have similar functionality: https://github.com/iKevinY/EulerPy

**Comment by jxu** [comment]
Ok I made a repo here https://github.com/jxu/project-euler-answer-checker
